name: Integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"
  schedule:
    - cron: '0 0 * * *'

jobs:
  php-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      COMPOSER_NO_INTERACTION: 1

    strategy:
      matrix:
        php: [8.4, 8.3, 8.2, 8.1, 8.0, 7.4, 7.3, 7.2]

    name: PHP${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          extensions: pdo_sqlite

      - name: Install dependencies
        run: |
          composer update --prefer-dist --no-progress
          composer update --prefer-dist --no-progress --working-dir=demo/bridge/monolog
          composer update --prefer-dist --no-progress --working-dir=demo/bridge/doctrine
          composer run --working-dir=demo/bridge/doctrine install-schema

      - name: Execute Unit Tests
        run: vendor/bin/phpunit --testsuite=Browser
